### ISSUE TITLE
Add `slot_index` property to entries in the `/signers` endpoint

### ISSUE THREAD

**Issue by hstove** [hirosystems/signer-metrics-api#40]
For this route: https://api.stg.hiro.so/signer-metrics/v1/cycles/96/signers?from=now-12h&to=now

The signers result has an unknown(?) sort order. It would be helpful to sort this by their index in the stacker set, or to at least return the index as a property

**Comment by zone117x** [comment]
It's currently sorted by `(weight, stacked_amount)`. I'll add a `slot_index` property. 

We could also add something like a `?sort_by=weight|slot_index|etc` query param.

**Comment by zone117x** [comment]
(Implementation note)
The sql migration should just drop the current table to trigger the existing runtime logic which will detect missing cycle signer sets, fetch them, and insert them (this time with the slot_index data). This is cleaner and less error-prone than an alter-table migration + missing slot_index detection + table updating logic.
